### ISSUE TITLE
Hairu

### ISSUE THREAD

**Issue by ertan-sahinoglu** [pagemachine/hairu#1]
Ich finde die extension gut, leider ist mir nach der installation aufgefallen, das keine deutsche übersetzung vorhanden ist. Ich würde es begrüßen, wenn ihr eine deutsche Übersetzung umsetzen würdet.

Vielen Dank im voraus.

Ertan Sahinglu

**Comment by mbrodala** [comment]
The extension is only in English ATM since we're aiming at an integration with the [TYPO3 Translation Server](http://translation.typo3.org/). We have created a [ticket](https://forge.typo3.org/issues/62942) accordingly but unfortunately there has been no response as of now. We'll try to get in contact with the TYPO3 Translation Team leaders.

Until then you create the following folder path and drop [these files](https://gist.github.com/mbrodala/99c18b1b1c76c06618c4) there:

`typo3conf/i10n/de/hairu/Resources/Private/Language`

After clearing the system caches the German translations will be activated. Please let us know if everything works.

**Comment by mbrodala** [comment]
Got response that it works, closing then.

**Comment by mbrodala** [comment]
We are now on the [TYPO3 Translation Server](http://translation.typo3.org/projects/TYPO3.TYPO3.ext.hairu/). :+1:
