### ISSUE TITLE
Login with E-Mail instead of Username

### ISSUE THREAD

**Issue by k2220** [pagemachine/hairu#47]
Hi, really great extension :). It would be really great if you could log in with the e-mail instead of username. Is that possible?

**Comment by mbrodala** [comment]
The easiest solution would be to set up your instance to have users created with their email address copied to the `fe_users.username` field. Of course, these then need to be kept in sync.

There's also the `username_column` option within the TYPO3 authentication services but you'll need to fiddle around at quite a lot of places to get this changed everywhere.

In any case there's nothing Hairu can do here since it just provides a frontend for login/logout. :-)
